services:
  postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  petklinik:
    image: backend:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/petclinic
      - IMAGE_GENERATOR_URL=http://ai:8081/generate
  ai:
    image: ai:1.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
